appName: notes-app
namespace: nginx

deployment:
  replicas: 1
  image: axm1k/notes-app-k8s
  containerPort: 8000

service:
  name: notes-app-service
  type: ClusterIP
  port: 8000
  targetPort: 8000

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false
