appName: notes-app
namespace: nginx

deployment:
  replicas: 1
  image: axm1k/notes-app-k8s
  containerPort: 8000

service:
  name: notes-app-service
  type: ClusterIP
  port: 8000
  targetPort: 8000

serviceAccount:
  create: false

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: notes.local
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"